# Title: jest-annotations-coverage
# Author: mattallty
# Date: 2021
# Availability: https://github.com/mattallty/jest-github-action

name: Jest Code Coverage

on:
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install npm
        run: npm ci

      - name: Run Jest
        run: npm run test -- --coverage unit.test.js
        
      - name: Run Coverage Action  
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: npm test -- unit.test.js