# Defaults to To-Do for issues and In Progress for pull requests
name: Auto-assign to Recipe App Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
    
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    name: Assign project
    steps:
      - uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/cse110-fa21-group15/cse110-fa21-group15/projects/1'
